# https://github.com/travis-ci/travis-ci/issues/9069
language: python
sudo: required
dist: xenial
python:
  - "3.7"
install:
  - pip install pyenv
  - pipenv install --dev
script:
  - pipenv run python test_tboard.py -v
